export default Object.freeze({
  // ToDo actions
  SET_IS_OPEN_TASK_MODAL: "SET_IS_OPEN_TASK_MODAL",
  SET_IS_OPEN_CONFIRM_MODAL: "SET_IS_OPEN_CONFIRM_MODAL",
  SET_EDITABLE_TASK: "SET_EDITABLE_TASK",
  ADD_TASK: "ADD_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  SELECT_TASK: "SELECT_TASK",
  SELECT_ALL_TASKS: "SELECT_ALL_TASKS",
  DELETE_SELECTED_TASKS: "DELETE_SELECTED_TASKS",
  SET_TASKS: "SET_TASKS",
  // SingleTask actions
  SET_SINGLE_TASK: "SET_SINGLE_TASK",
  REMOVE_SINGLE_TASK: "REMOVE_SINGLE_TASK",
  TOGGLE_HIDE_MODAL: "TOGGLE_HIDE_MODAL",
  // actions
  SET_LOADING: "SET_LOADING",
  REMOVE_LOADING: "REMOVE_LOADING",
});
