export default Object.freeze({
  // global types
  SET_LOADING: "SET_LOADING",
  REMOVE_LOADING: "REMOVE_LOADING",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  REMOVE_ERROR_MESSAGE: "REMOVE_ERROR_MESSAGE",
  SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
  REMOVE_SUCCESS_MESSAGE: "REMOVE_SUCCESS_MESSAGE",
  OPEN_ERROR_MESSAGE_ALERT: "OPEN_ERROR_MESSAGE_ALERT",
  CLOSE_ERROR_MESSAGE_ALERT: "CLOSE_ERROR_MESSAGE_ALERT",
  // ToDo types
  SET_IS_OPEN_TASK_MODAL: "SET_IS_OPEN_TASK_MODAL",
  SET_IS_OPEN_CONFIRM_MODAL: "SET_IS_OPEN_CONFIRM_MODAL",
  SET_EDITABLE_TASK: "SET_EDITABLE_TASK",
  ADD_TASK: "ADD_TASK",
  EDIT_TASK: "EDIT_TASK",
  DELETE_TASK: "DELETE_TASK",
  SELECT_TASK: "SELECT_TASK",
  SELECT_ALL_TASKS: "SELECT_ALL_TASKS",
  DELETE_SELECTED_TASKS: "DELETE_SELECTED_TASKS",
  SET_TASKS: "SET_TASKS",
  RESET_TODO_DATA: "RESET_TODO_DATA",
  // SingleTask types
  SET_SINGLE_TASK: "SET_SINGLE_TASK",
  TOGGLE_HIDE_MODAL: "TOGGLE_HIDE_MODAL",
  RESET_SINGLE_TASK_DATA: "RESET_SINGLE_TASK_DATA",
  // ContactForm types
  CHANGE: "CHANGE",
  RESET_CONTACT_FORM_DATA: "RESET_CONTACT_FORM_DATA",
  // AddEditTaskModal types
  CHANGE_TASK: "CHANGE_TASK",
  CHANGE_DATE: "CHANGE_DATE",
  RESET_MODAL_DATA: "RESET_MODAL_DATA",
});
